Patch #317
ff=1, fp=0, pf=6, pp=31
Modified method: org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolver:doSolve()D#320
Modified method: org.apache.commons.math.exception.util.ExceptionContext:buildMessage(Ljava/util/Locale;Ljava/lang/String;)Ljava/lang/String;#171
Modified method: org.apache.commons.math.exception.util.ExceptionContext:buildMessage(Ljava/util/Locale;Ljava/lang/String;)Ljava/lang/String;#175
Modified method: org.apache.commons.math.exception.util.ExceptionContext:buildMessage(Ljava/util/Locale;Ljava/lang/String;)Ljava/lang/String;#182
------------------
[FAIL->FAIL] org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest#testIssue716
[PASS->FAIL] org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest#testConvergenceOnFunctionAccuracy
[PASS->FAIL] org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest#testSolutionAboveSide
[PASS->FAIL] org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest#testSolutionBelowSide
[PASS->FAIL] org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest#testSolutionLeftSide
[PASS->FAIL] org.apache.commons.math.analysis.solvers.BracketingNthOrderBrentSolverTest#testSolutionRightSide
[PASS->FAIL] org.apache.commons.math.exception.util.ExceptionContextTest#testMessageChain
